### ISSUE TITLE
suits not loading

### ISSUE THREAD

**Issue by FireFist98** [Tkachov/Overstrike#20]
im using Overstrike version 1.4.2, i downloaded some suits from Nexus mod and put them into Overstrike install menu, after it finished downloading i double-checked that it works using the Suit Menu but after loading the game it only shows my a couple of suits, the only thing i can think of is there is a "Max Suits" option in the settings
![Screenshot_62](https://github.com/Tkachov/Overstrike/assets/146864511/4d23c8fd-58b9-4ca9-a79c-e72a29d97e05)
![Screenshot_63](https://github.com/Tkachov/Overstrike/assets/146864511/c05dc896-a6e0-4e4f-9be9-94d7e0c8c56e)

**Comment by Tkachov** [comment]
This is a game bug, not Overstrike. Scrollbar doesn't scroll lower, but if you press [S] on keyboard, it will list the next row.
