### ISSUE TITLE
Documentation on DSAR file format

### ISSUE THREAD

**Issue by Foul-Tarnished** [Tkachov/Overstrike#25]
Hi, I'm trying to unpack Ghost of Tsushima Director's Cut (PC version) files.

They are in .psarc format, and tried to use this tool to decrypt them :
https://github.com/MilchRatchet/PSArcInterface/issues/4

But apparently, they are DSAR files with psarc inside, or the other way around idk
Could you help us decrypt these ? Do you know any other tool who could help ?

Thank you

[gapack_misc_b.zip](https://github.com/Tkachov/Overstrike/files/15366329/gapack_misc_b.zip)

**Comment by Tkachov** [comment]
Hi!

Yep, they look similar to what we have in MSMR/MM/RCRA.

I don't think there are docs, except maybe for this:
https://github.com/yretenai/rivet/blob/develop/docs/format/dsar.txt

There's a C# implementation in Overstrike that knows how to decode (read) files from DSARs that are used in Insomniac's games:
https://github.com/Tkachov/Overstrike/blob/main/DAT1/DSAR.cs

And there's a Python implementation in my other repo, ALERT. It knows how to encode (write) files into DSAR too, but only with LZ4 compression:
https://github.com/Tkachov/ALERT/blob/main/dsar_codec.py

I've tried running the latter on your file, and it showed "unsupported DSAR compression type: 254" message. It seems that in GoT DSARs they use a compression algorithm that is different from MSMR/MM/RCRA. So, it's possible that there's no public implementation for these.

I'm not interested in modding GoT, so this is all I can do for you. I guess someone with reverse engineering skills can figure out how game's own .exe decodes those DSARs, and make a tool for that.

As this is not exactly an Overstrike issue, I'd close it in 24 hours.

**Comment by Foul-Tarnished** [comment]
> Hi!
> 
> Yep, they look similar to what we have in MSMR/MM/RCRA.
> 
> I don't think there are docs, except maybe for this: https://github.com/yretenai/rivet/blob/develop/docs/format/dsar.txt
> 
> There's a C# implementation in Overstrike that knows how to decode (read) files from DSARs that are used in Insomniac's games: https://github.com/Tkachov/Overstrike/blob/main/DAT1/DSAR.cs
> 
> And there's a Python implementation in my other repo, ALERT. It knows how to encode (write) files into DSAR too, but only with LZ4 compression: https://github.com/Tkachov/ALERT/blob/main/dsar_codec.py
> 
> I've tried running the latter on your file, and it showed "unsupported DSAR compression type: 254" message. It seems that in GoT DSARs they use a compression algorithm that is different from MSMR/MM/RCRA. So, it's possible that there's no public implementation for these.
> 
> I'm not interested in modding GoT, so this is all I can do for you. I guess someone with reverse engineering skills can figure out how game's own .exe decodes those DSARs, and make a tool for that.
> 
> As this is not exactly an Overstrike issue, I'd close it in 24 hours.

Thank you!

Last question, ever heard or .sps file format ?

FYI, I was able to unpack partially using QuickBMS app
and this psarc.txt "plugin" file [psarc.txt](https://github.com/MilchRatchet/PSArcInterface/files/15366584/psarc.txt)
(from https://reshax.com/topic/746-ghost-of-tsushima-pc-psarc-archive/?do=findComment&comment=3421&_rid=2840)

So far, the "bitmaps" psarc archives are full of "**.sps**" files.
Ever heard of that format ?
[bitmaps.zip](https://github.com/MilchRatchet/PSArcInterface/files/15366590/bitmaps.zip)


Thank you

**Comment by Tkachov** [comment]
Nope, I've not seen XTBS or .sps files before.
